[2022-08-11 22:02:53,416] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-11T22:02:37.754995+00:00 [queued]>
[2022-08-11 22:02:53,443] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-11T22:02:37.754995+00:00 [queued]>
[2022-08-11 22:02:53,443] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 22:02:53,444] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-11 22:02:53,446] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 22:02:53,481] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_into_xlsx> on 2022-08-11 22:02:37.754995+00:00
[2022-08-11 22:02:53,492] {standard_task_runner.py:52} INFO - Started process 1878 to run task
[2022-08-11 22:02:53,500] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'convert_xls_into_xlsx', 'manual__2022-08-11T22:02:37.754995+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmphh9xkrq0', '--error-file', '/tmp/tmpcl0nihyl']
[2022-08-11 22:02:53,502] {standard_task_runner.py:80} INFO - Job 29: Subtask convert_xls_into_xlsx
[2022-08-11 22:02:53,658] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-11T22:02:37.754995+00:00 [running]> on host 53e7d4a502e6
[2022-08-11 22:02:53,905] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_into_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T22:02:37.754995+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T22:02:37.754995+00:00
[2022-08-11 22:02:53,909] {ETL_Raizen.py:48} INFO - Converting file .xls into .xlsx using libreoffice
[2022-08-11 22:02:59,677] {ETL_Raizen.py:50} INFO - File .xls succesfully converted into .xlsx
[2022-08-11 22:02:59,678] {python.py:173} INFO - Done. Returned value was: None
[2022-08-11 22:02:59,728] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=convert_xls_into_xlsx, execution_date=20220811T220237, start_date=20220811T220253, end_date=20220811T220259
[2022-08-11 22:02:59,825] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 22:02:59,907] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
