[2022-08-11 22:33:02,925] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-11T22:32:34.972598+00:00 [queued]>
[2022-08-11 22:33:02,954] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-11T22:32:34.972598+00:00 [queued]>
[2022-08-11 22:33:02,955] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 22:33:02,958] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-11 22:33:02,958] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 22:33:03,027] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_into_xlsx> on 2022-08-11 22:32:34.972598+00:00
[2022-08-11 22:33:03,051] {standard_task_runner.py:52} INFO - Started process 3533 to run task
[2022-08-11 22:33:03,061] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'convert_xls_into_xlsx', 'manual__2022-08-11T22:32:34.972598+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmp5h232nu7', '--error-file', '/tmp/tmp2qhiu1pa']
[2022-08-11 22:33:03,078] {standard_task_runner.py:80} INFO - Job 56: Subtask convert_xls_into_xlsx
[2022-08-11 22:33:03,385] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-11T22:32:34.972598+00:00 [running]> on host 53e7d4a502e6
[2022-08-11 22:33:03,693] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_into_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T22:32:34.972598+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T22:32:34.972598+00:00
[2022-08-11 22:33:03,699] {ETL_Raizen.py:48} INFO - Converting file .xls into .xlsx using libreoffice
[2022-08-11 22:33:16,339] {ETL_Raizen.py:50} INFO - File .xls succesfully converted into .xlsx
[2022-08-11 22:33:16,343] {python.py:173} INFO - Done. Returned value was: None
[2022-08-11 22:33:16,389] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=convert_xls_into_xlsx, execution_date=20220811T223234, start_date=20220811T223302, end_date=20220811T223316
[2022-08-11 22:33:16,473] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 22:33:16,575] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
