[2022-08-12 19:49:44,914] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-12T19:49:36.610250+00:00 [queued]>
[2022-08-12 19:49:44,929] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-12T19:49:36.610250+00:00 [queued]>
[2022-08-12 19:49:44,930] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 19:49:44,931] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-12 19:49:44,931] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 19:49:44,952] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_into_xlsx> on 2022-08-12 19:49:36.610250+00:00
[2022-08-12 19:49:44,982] {standard_task_runner.py:52} INFO - Started process 408 to run task
[2022-08-12 19:49:44,988] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'convert_xls_into_xlsx', 'manual__2022-08-12T19:49:36.610250+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpknx9nz70', '--error-file', '/tmp/tmp856a85sz']
[2022-08-12 19:49:44,990] {standard_task_runner.py:80} INFO - Job 219: Subtask convert_xls_into_xlsx
[2022-08-12 19:49:45,083] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-12T19:49:36.610250+00:00 [running]> on host 3c4d8e0d9450
[2022-08-12 19:49:45,181] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_into_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T19:49:36.610250+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-12T19:49:36.610250+00:00
[2022-08-12 19:49:45,184] {ETL_Raizen.py:47} INFO - Converting file .xls into .xlsx using libreoffice
[2022-08-12 19:49:49,018] {ETL_Raizen.py:49} INFO - File .xls succesfully converted into .xlsx
[2022-08-12 19:49:49,019] {python.py:173} INFO - Done. Returned value was: None
[2022-08-12 19:49:49,039] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=convert_xls_into_xlsx, execution_date=20220812T194936, start_date=20220812T194944, end_date=20220812T194949
[2022-08-12 19:49:49,061] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-12 19:49:49,104] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
