[2022-08-12 23:30:03,087] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.download_raw_data scheduled__2022-08-12T22:30:00+00:00 [queued]>
[2022-08-12 23:30:03,103] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.download_raw_data scheduled__2022-08-12T22:30:00+00:00 [queued]>
[2022-08-12 23:30:03,104] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 23:30:03,104] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-12 23:30:03,105] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 23:30:03,126] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): download_raw_data> on 2022-08-12 22:30:00+00:00
[2022-08-12 23:30:03,140] {standard_task_runner.py:52} INFO - Started process 10094 to run task
[2022-08-12 23:30:03,145] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'download_raw_data', 'scheduled__2022-08-12T22:30:00+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpqm6bb_ly', '--error-file', '/tmp/tmplt_nlbyi']
[2022-08-12 23:30:03,147] {standard_task_runner.py:80} INFO - Job 270: Subtask download_raw_data
[2022-08-12 23:30:03,231] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.download_raw_data scheduled__2022-08-12T22:30:00+00:00 [running]> on host 4bbb34367c41
[2022-08-12 23:30:03,450] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=download_raw_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T22:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-12T22:30:00+00:00
[2022-08-12 23:30:03,452] {ETL_Raizen.py:40} INFO - Downloading .xls raw data
[2022-08-12 23:31:24,284] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-08-12 23:31:24,302] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 10094. PIDs of all processes in the group: [10094]
[2022-08-12 23:31:24,303] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 10094
[2022-08-12 23:31:24,308] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-08-12 23:31:24,437] {process_utils.py:75} INFO - Process psutil.Process(pid=10094, status='terminated', exitcode=0, started='23:30:02') (10094) terminated with exit code 0
