[2022-08-12 11:04:12,169] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-12T11:03:58.044044+00:00 [queued]>
[2022-08-12 11:04:12,179] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-12T11:03:58.044044+00:00 [queued]>
[2022-08-12 11:04:12,179] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 11:04:12,180] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-12 11:04:12,181] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 11:04:12,197] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_into_xlsx> on 2022-08-12 11:03:58.044044+00:00
[2022-08-12 11:04:12,205] {standard_task_runner.py:52} INFO - Started process 120 to run task
[2022-08-12 11:04:12,209] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'convert_xls_into_xlsx', 'manual__2022-08-12T11:03:58.044044+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpe8kir8jd', '--error-file', '/tmp/tmp2zz3nqkk']
[2022-08-12 11:04:12,210] {standard_task_runner.py:80} INFO - Job 126: Subtask convert_xls_into_xlsx
[2022-08-12 11:04:12,294] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-12T11:03:58.044044+00:00 [running]> on host a471224fadbb
[2022-08-12 11:04:12,380] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_into_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T11:03:58.044044+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-12T11:03:58.044044+00:00
[2022-08-12 11:04:12,382] {ETL_Raizen.py:47} INFO - Converting file .xls into .xlsx using libreoffice
[2022-08-12 11:04:19,705] {ETL_Raizen.py:49} INFO - File .xls succesfully converted into .xlsx
[2022-08-12 11:04:19,706] {python.py:173} INFO - Done. Returned value was: None
[2022-08-12 11:04:19,729] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=convert_xls_into_xlsx, execution_date=20220812T110358, start_date=20220812T110412, end_date=20220812T110419
[2022-08-12 11:04:19,775] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-12 11:04:19,856] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
