[2022-08-12 11:15:43,712] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-12T11:15:36.213607+00:00 [queued]>
[2022-08-12 11:15:43,730] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-12T11:15:36.213607+00:00 [queued]>
[2022-08-12 11:15:43,731] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 11:15:43,733] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-12 11:15:43,733] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 11:15:43,753] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): convert_xls_into_xlsx> on 2022-08-12 11:15:36.213607+00:00
[2022-08-12 11:15:43,759] {standard_task_runner.py:52} INFO - Started process 963 to run task
[2022-08-12 11:15:43,763] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'convert_xls_into_xlsx', 'manual__2022-08-12T11:15:36.213607+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmphecbu0_y', '--error-file', '/tmp/tmpqzss4nb9']
[2022-08-12 11:15:43,765] {standard_task_runner.py:80} INFO - Job 140: Subtask convert_xls_into_xlsx
[2022-08-12 11:15:43,842] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.convert_xls_into_xlsx manual__2022-08-12T11:15:36.213607+00:00 [running]> on host a471224fadbb
[2022-08-12 11:15:43,925] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=convert_xls_into_xlsx
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T11:15:36.213607+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-12T11:15:36.213607+00:00
[2022-08-12 11:15:43,927] {ETL_Raizen.py:46} INFO - Converting file .xls into .xlsx using libreoffice
[2022-08-12 11:15:46,988] {ETL_Raizen.py:48} INFO - File .xls succesfully converted into .xlsx
[2022-08-12 11:15:46,989] {python.py:173} INFO - Done. Returned value was: None
[2022-08-12 11:15:47,006] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=convert_xls_into_xlsx, execution_date=20220812T111536, start_date=20220812T111543, end_date=20220812T111547
[2022-08-12 11:15:47,031] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-12 11:15:47,085] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
