[2022-08-12 11:09:32,114] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.creating_raw_data_dir manual__2022-08-12T11:09:30.533518+00:00 [queued]>
[2022-08-12 11:09:32,128] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_Raízen.creating_raw_data_dir manual__2022-08-12T11:09:30.533518+00:00 [queued]>
[2022-08-12 11:09:32,129] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 11:09:32,129] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-12 11:09:32,130] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 11:09:32,147] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): creating_raw_data_dir> on 2022-08-12 11:09:30.533518+00:00
[2022-08-12 11:09:32,154] {standard_task_runner.py:52} INFO - Started process 553 to run task
[2022-08-12 11:09:32,158] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_Raízen', 'creating_raw_data_dir', 'manual__2022-08-12T11:09:30.533518+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Raizen.py', '--cfg-path', '/tmp/tmpkkm2dtb4', '--error-file', '/tmp/tmply6cffgs']
[2022-08-12 11:09:32,159] {standard_task_runner.py:80} INFO - Job 133: Subtask creating_raw_data_dir
[2022-08-12 11:09:32,229] {task_command.py:369} INFO - Running <TaskInstance: ETL_Raízen.creating_raw_data_dir manual__2022-08-12T11:09:30.533518+00:00 [running]> on host a471224fadbb
[2022-08-12 11:09:32,307] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_Raízen
AIRFLOW_CTX_TASK_ID=creating_raw_data_dir
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T11:09:30.533518+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-12T11:09:30.533518+00:00
[2022-08-12 11:09:32,309] {ETL_Raizen.py:28} INFO - Dir already exists
[2022-08-12 11:09:32,309] {python.py:173} INFO - Done. Returned value was: None
[2022-08-12 11:09:32,325] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Raízen, task_id=creating_raw_data_dir, execution_date=20220812T110930, start_date=20220812T110932, end_date=20220812T110932
[2022-08-12 11:09:32,371] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-12 11:09:32,477] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
